//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountStatus complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AccountStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountIdentification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accountBalance" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="minimumPayment" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountStatus", propOrder = {
        "accountIdentification",
        "accountName",
        "accountBalance",
        "minimumPayment"
})
public class AccountStatus {

    protected String accountIdentification;
    protected String accountName;
    protected Currency accountBalance;
    protected Currency minimumPayment;

    /**
     * Gets the value of the accountIdentification property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountIdentification() {
        return accountIdentification;
    }

    /**
     * Sets the value of the accountIdentification property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountIdentification(String value) {
        this.accountIdentification = value;
    }

    /**
     * Gets the value of the accountName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the accountBalance property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getAccountBalance() {
        return accountBalance;
    }

    /**
     * Sets the value of the accountBalance property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setAccountBalance(Currency value) {
        this.accountBalance = value;
    }

    /**
     * Gets the value of the minimumPayment property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getMinimumPayment() {
        return minimumPayment;
    }

    /**
     * Sets the value of the minimumPayment property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setMinimumPayment(Currency value) {
        this.minimumPayment = value;
    }

}
