//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for AddChargesMonthlyList complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AddChargesMonthlyList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AddChargeMonthlyItems" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}AddChargeMonthlyItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddChargesMonthlyList", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "addChargeMonthlyItems"
})
public class AddChargesMonthlyList {

    @XmlElement(name = "AddChargeMonthlyItems")
    protected List<AddChargeMonthlyItem> addChargeMonthlyItems;

    /**
     * Gets the value of the addChargeMonthlyItems property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the addChargeMonthlyItems property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddChargeMonthlyItems().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddChargeMonthlyItem }
     */
    public List<AddChargeMonthlyItem> getAddChargeMonthlyItems() {
        if (addChargeMonthlyItems == null) {
            addChargeMonthlyItems = new ArrayList<AddChargeMonthlyItem>();
        }
        return this.addChargeMonthlyItems;
    }

}
