//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BankBatch complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BankBatch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}Batch"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firstSalesSeqNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastSalesSeqNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="depSlip" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}DepositSlip" minOccurs="0"/&gt;
 *         &lt;element name="salesBatch" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}SalesBatch" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="seqNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankBatch", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "firstSalesSeqNo",
        "lastSalesSeqNo",
        "depSlip",
        "salesBatch"
})
public class BankBatch
        extends Batch {

    protected String firstSalesSeqNo;
    protected String lastSalesSeqNo;
    protected DepositSlip depSlip;
    protected List<SalesBatch> salesBatch;
    @XmlAttribute(name = "seqNo")
    protected String seqNo;

    /**
     * Gets the value of the firstSalesSeqNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFirstSalesSeqNo() {
        return firstSalesSeqNo;
    }

    /**
     * Sets the value of the firstSalesSeqNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFirstSalesSeqNo(String value) {
        this.firstSalesSeqNo = value;
    }

    /**
     * Gets the value of the lastSalesSeqNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastSalesSeqNo() {
        return lastSalesSeqNo;
    }

    /**
     * Sets the value of the lastSalesSeqNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastSalesSeqNo(String value) {
        this.lastSalesSeqNo = value;
    }

    /**
     * Gets the value of the depSlip property.
     *
     * @return possible object is
     * {@link DepositSlip }
     */
    public DepositSlip getDepSlip() {
        return depSlip;
    }

    /**
     * Sets the value of the depSlip property.
     *
     * @param value allowed object is
     *              {@link DepositSlip }
     */
    public void setDepSlip(DepositSlip value) {
        this.depSlip = value;
    }

    /**
     * Gets the value of the salesBatch property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the salesBatch property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesBatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesBatch }
     */
    public List<SalesBatch> getSalesBatch() {
        if (salesBatch == null) {
            salesBatch = new ArrayList<SalesBatch>();
        }
        return this.salesBatch;
    }

    /**
     * Gets the value of the seqNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSeqNo(String value) {
        this.seqNo = value;
    }

}
