//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseVendReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BaseVendReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="resource" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Resource" minOccurs="0"/&gt;
 *         &lt;element name="idMethod" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}VendIDMethod" minOccurs="0"/&gt;
 *         &lt;element name="tokenDeliveryMethod" type="{http://www.conlog.co.za/xmlvend/base-ext/2.1.1/schema}TokenDeliveryMethod" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseVendReq", propOrder = {
        "resource",
        "idMethod",
        "tokenDeliveryMethod"
})
@XmlSeeAlso({
        MeterSpecificEngReq.class,
        CmftReq.class,
        FBEReq.class,
        MeterCreditTransferReq.class,
        FreeIssueReq.class,
        CancelVendReq.class,
        AbstractCreditVendReq.class
})
public class BaseVendReq
        extends BaseReq {

    protected Resource resource;
    protected VendIDMethod idMethod;
    protected TokenDeliveryMethod tokenDeliveryMethod;

    /**
     * Gets the value of the resource property.
     *
     * @return possible object is
     * {@link Resource }
     */
    public Resource getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     *
     * @param value allowed object is
     *              {@link Resource }
     */
    public void setResource(Resource value) {
        this.resource = value;
    }

    /**
     * Gets the value of the idMethod property.
     *
     * @return possible object is
     * {@link VendIDMethod }
     */
    public VendIDMethod getIdMethod() {
        return idMethod;
    }

    /**
     * Sets the value of the idMethod property.
     *
     * @param value allowed object is
     *              {@link VendIDMethod }
     */
    public void setIdMethod(VendIDMethod value) {
        this.idMethod = value;
    }

    /**
     * Gets the value of the tokenDeliveryMethod property.
     *
     * @return possible object is
     * {@link TokenDeliveryMethod }
     */
    public TokenDeliveryMethod getTokenDeliveryMethod() {
        return tokenDeliveryMethod;
    }

    /**
     * Sets the value of the tokenDeliveryMethod property.
     *
     * @param value allowed object is
     *              {@link TokenDeliveryMethod }
     */
    public void setTokenDeliveryMethod(TokenDeliveryMethod value) {
        this.tokenDeliveryMethod = value;
    }

}
