//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BaseReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vendingServerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clientID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}DeviceID" minOccurs="0"/&gt;
 *         &lt;element name="terminalID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}DeviceID" minOccurs="0"/&gt;
 *         &lt;element name="msgID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MsgID" minOccurs="0"/&gt;
 *         &lt;element name="authCred" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}AuthCred" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseReq", propOrder = {
        "vendingServerID",
        "clientID",
        "terminalID",
        "msgID",
        "authCred"
})
@XmlSeeAlso({
        ConfirmMeterReq.class,
        CustReportFaultReq.class,
        UpdateMeterKeyReq.class,
        NonMeterSpecificEngReq.class,
        GetVendingServerStateReq.class,
        MakeMerchantDepositReq.class,
        ReverseMerchantDepositReq.class,
        AdviceReq.class,
        ConfirmCustomerReq.class,
        ReprintReq.class,
        VerifyReq.class,
        PayAccReq.class,
        VendorStatementReq.class,
        DepositReq.class,
        ReprintDepositReq.class,
        CancelPayAccountReq.class,
        EndBatchReq.class,
        TotalBatchReq.class,
        StartBatchReq.class,
        ReprintEndBatchReq.class,
        BaseVendReq.class
})
public class BaseReq {

    protected String vendingServerID;
    protected DeviceID clientID;
    protected DeviceID terminalID;
    protected MsgID msgID;
    protected AuthCred authCred;

    /**
     * Gets the value of the vendingServerID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVendingServerID() {
        return vendingServerID;
    }

    /**
     * Sets the value of the vendingServerID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVendingServerID(String value) {
        this.vendingServerID = value;
    }

    /**
     * Gets the value of the clientID property.
     *
     * @return possible object is
     * {@link DeviceID }
     */
    public DeviceID getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     *
     * @param value allowed object is
     *              {@link DeviceID }
     */
    public void setClientID(DeviceID value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the terminalID property.
     *
     * @return possible object is
     * {@link DeviceID }
     */
    public DeviceID getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     *
     * @param value allowed object is
     *              {@link DeviceID }
     */
    public void setTerminalID(DeviceID value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the msgID property.
     *
     * @return possible object is
     * {@link MsgID }
     */
    public MsgID getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     *
     * @param value allowed object is
     *              {@link MsgID }
     */
    public void setMsgID(MsgID value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the authCred property.
     *
     * @return possible object is
     * {@link AuthCred }
     */
    public AuthCred getAuthCred() {
        return authCred;
    }

    /**
     * Sets the value of the authCred property.
     *
     * @param value allowed object is
     *              {@link AuthCred }
     */
    public void setAuthCred(AuthCred value) {
        this.authCred = value;
    }

}
