//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseVendResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BaseVendResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="clientStatus" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}ClientStatus" minOccurs="0"/&gt;
 *         &lt;element name="vendor" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}VendorDetail" minOccurs="0"/&gt;
 *         &lt;element name="custVendDetail" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CustVendDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseVendResp", propOrder = {
        "clientStatus",
        "vendor",
        "custVendDetail"
})
@XmlSeeAlso({
        UpdateMeterKeyResp.class,
        CmftResp.class,
        MeterSpecificEngResp.class,
        CancelPayAccountResp.class,
        MeterCreditTransferResp.class,
        CancelVendResp.class,
        VerifyResp.class,
        PayAccResp.class,
        CreditVendResp.class
})
public class BaseVendResp
        extends BaseResp {

    protected ClientStatus clientStatus;
    protected VendorDetail vendor;
    protected CustVendDetail custVendDetail;

    /**
     * Gets the value of the clientStatus property.
     *
     * @return possible object is
     * {@link ClientStatus }
     */
    public ClientStatus getClientStatus() {
        return clientStatus;
    }

    /**
     * Sets the value of the clientStatus property.
     *
     * @param value allowed object is
     *              {@link ClientStatus }
     */
    public void setClientStatus(ClientStatus value) {
        this.clientStatus = value;
    }

    /**
     * Gets the value of the vendor property.
     *
     * @return possible object is
     * {@link VendorDetail }
     */
    public VendorDetail getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     *
     * @param value allowed object is
     *              {@link VendorDetail }
     */
    public void setVendor(VendorDetail value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the custVendDetail property.
     *
     * @return possible object is
     * {@link CustVendDetail }
     */
    public CustVendDetail getCustVendDetail() {
        return custVendDetail;
    }

    /**
     * Sets the value of the custVendDetail property.
     *
     * @param value allowed object is
     *              {@link CustVendDetail }
     */
    public void setCustVendDetail(CustVendDetail value) {
        this.custVendDetail = value;
    }

}
