//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BaseResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BaseResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="clientID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}DeviceID" minOccurs="0"/&gt;
 *         &lt;element name="serverID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}DeviceID" minOccurs="0"/&gt;
 *         &lt;element name="terminalID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}DeviceID" minOccurs="0"/&gt;
 *         &lt;element name="reqMsgID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MsgID" minOccurs="0"/&gt;
 *         &lt;element name="respDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="dispHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="operatorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="custMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="utility" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}UtilityDetail" minOccurs="0"/&gt;
 *         &lt;element name="CurrencyExchangeRates" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}CurrencyExchangeRates" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseResp", propOrder = {
        "clientID",
        "serverID",
        "terminalID",
        "reqMsgID",
        "respDateTime",
        "dispHeader",
        "operatorMsg",
        "custMsg",
        "utility",
        "currencyExchangeRates"
})
@XmlSeeAlso({
        ConfirmMeterResp.class,
        CustReportFaultResp.class,
        NonMeterSpecificEngResp.class,
        GetVendingServerStateResp.class,
        MakeMerchantDepositResp.class,
        ReverseMerchantDepositResp.class,
        AdviceResp.class,
        XMLVendFaultResp.class,
        ConfirmCustomerResp.class,
        ReprintResp.class,
        VendorStatementResp.class,
        DepositResp.class,
        ReprintDepositResp.class,
        ReprintEndBatchResp.class,
        BaseVendResp.class,
        StartBatchResp.class,
        TotalBatchResp.class,
        EndBatchResp.class
})
public class BaseResp {

    protected DeviceID clientID;
    protected DeviceID serverID;
    protected DeviceID terminalID;
    protected MsgID reqMsgID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar respDateTime;
    protected String dispHeader;
    protected String operatorMsg;
    protected String custMsg;
    protected UtilityDetail utility;
    @XmlElement(name = "CurrencyExchangeRates")
    protected CurrencyExchangeRates currencyExchangeRates;

    /**
     * Gets the value of the clientID property.
     *
     * @return possible object is
     * {@link DeviceID }
     */
    public DeviceID getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     *
     * @param value allowed object is
     *              {@link DeviceID }
     */
    public void setClientID(DeviceID value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the serverID property.
     *
     * @return possible object is
     * {@link DeviceID }
     */
    public DeviceID getServerID() {
        return serverID;
    }

    /**
     * Sets the value of the serverID property.
     *
     * @param value allowed object is
     *              {@link DeviceID }
     */
    public void setServerID(DeviceID value) {
        this.serverID = value;
    }

    /**
     * Gets the value of the terminalID property.
     *
     * @return possible object is
     * {@link DeviceID }
     */
    public DeviceID getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     *
     * @param value allowed object is
     *              {@link DeviceID }
     */
    public void setTerminalID(DeviceID value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the reqMsgID property.
     *
     * @return possible object is
     * {@link MsgID }
     */
    public MsgID getReqMsgID() {
        return reqMsgID;
    }

    /**
     * Sets the value of the reqMsgID property.
     *
     * @param value allowed object is
     *              {@link MsgID }
     */
    public void setReqMsgID(MsgID value) {
        this.reqMsgID = value;
    }

    /**
     * Gets the value of the respDateTime property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getRespDateTime() {
        return respDateTime;
    }

    /**
     * Sets the value of the respDateTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setRespDateTime(XMLGregorianCalendar value) {
        this.respDateTime = value;
    }

    /**
     * Gets the value of the dispHeader property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDispHeader() {
        return dispHeader;
    }

    /**
     * Sets the value of the dispHeader property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDispHeader(String value) {
        this.dispHeader = value;
    }

    /**
     * Gets the value of the operatorMsg property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOperatorMsg() {
        return operatorMsg;
    }

    /**
     * Sets the value of the operatorMsg property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOperatorMsg(String value) {
        this.operatorMsg = value;
    }

    /**
     * Gets the value of the custMsg property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustMsg() {
        return custMsg;
    }

    /**
     * Sets the value of the custMsg property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustMsg(String value) {
        this.custMsg = value;
    }

    /**
     * Gets the value of the utility property.
     *
     * @return possible object is
     * {@link UtilityDetail }
     */
    public UtilityDetail getUtility() {
        return utility;
    }

    /**
     * Sets the value of the utility property.
     *
     * @param value allowed object is
     *              {@link UtilityDetail }
     */
    public void setUtility(UtilityDetail value) {
        this.utility = value;
    }

    /**
     * Gets the value of the currencyExchangeRates property.
     *
     * @return possible object is
     * {@link CurrencyExchangeRates }
     */
    public CurrencyExchangeRates getCurrencyExchangeRates() {
        return currencyExchangeRates;
    }

    /**
     * Sets the value of the currencyExchangeRates property.
     *
     * @param value allowed object is
     *              {@link CurrencyExchangeRates }
     */
    public void setCurrencyExchangeRates(CurrencyExchangeRates value) {
        this.currencyExchangeRates = value;
    }

}
