//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BatchReport complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BatchReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="txTotal" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}TxTotal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="operatorTotal" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}OperatorTotal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="payTypeTotal" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}PayTypeTotal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="resTot" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}ResourceTotal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchReport", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "txTotal",
        "operatorTotal",
        "payTypeTotal",
        "resTot"
})
public class BatchReport {

    protected List<TxTotal> txTotal;
    protected List<OperatorTotal> operatorTotal;
    protected List<PayTypeTotal> payTypeTotal;
    protected List<ResourceTotal> resTot;

    /**
     * Gets the value of the txTotal property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the txTotal property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxTotal().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TxTotal }
     */
    public List<TxTotal> getTxTotal() {
        if (txTotal == null) {
            txTotal = new ArrayList<TxTotal>();
        }
        return this.txTotal;
    }

    /**
     * Gets the value of the operatorTotal property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the operatorTotal property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperatorTotal().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperatorTotal }
     */
    public List<OperatorTotal> getOperatorTotal() {
        if (operatorTotal == null) {
            operatorTotal = new ArrayList<OperatorTotal>();
        }
        return this.operatorTotal;
    }

    /**
     * Gets the value of the payTypeTotal property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the payTypeTotal property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayTypeTotal().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayTypeTotal }
     */
    public List<PayTypeTotal> getPayTypeTotal() {
        if (payTypeTotal == null) {
            payTypeTotal = new ArrayList<PayTypeTotal>();
        }
        return this.payTypeTotal;
    }

    /**
     * Gets the value of the resTot property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the resTot property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResTot().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceTotal }
     */
    public List<ResourceTotal> getResTot() {
        if (resTot == null) {
            resTot = new ArrayList<ResourceTotal>();
        }
        return this.resTot;
    }

}
