//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Batch complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Batch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ended" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="batchTot" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="totTax" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Tax" minOccurs="0"/&gt;
 *         &lt;element name="batchReport" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}BatchReport" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Batch", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "started",
        "ended",
        "batchTot",
        "totTax",
        "batchReport"
})
@XmlSeeAlso({
        ShiftBatch.class,
        SalesBatch.class,
        BankBatch.class
})
public abstract class Batch {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar started;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ended;
    protected Currency batchTot;
    protected Tax totTax;
    protected BatchReport batchReport;

    /**
     * Gets the value of the started property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getStarted() {
        return started;
    }

    /**
     * Sets the value of the started property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStarted(XMLGregorianCalendar value) {
        this.started = value;
    }

    /**
     * Gets the value of the ended property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEnded() {
        return ended;
    }

    /**
     * Sets the value of the ended property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEnded(XMLGregorianCalendar value) {
        this.ended = value;
    }

    /**
     * Gets the value of the batchTot property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getBatchTot() {
        return batchTot;
    }

    /**
     * Sets the value of the batchTot property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setBatchTot(Currency value) {
        this.batchTot = value;
    }

    /**
     * Gets the value of the totTax property.
     *
     * @return possible object is
     * {@link Tax }
     */
    public Tax getTotTax() {
        return totTax;
    }

    /**
     * Sets the value of the totTax property.
     *
     * @param value allowed object is
     *              {@link Tax }
     */
    public void setTotTax(Tax value) {
        this.totTax = value;
    }

    /**
     * Gets the value of the batchReport property.
     *
     * @return possible object is
     * {@link BatchReport }
     */
    public BatchReport getBatchReport() {
        return batchReport;
    }

    /**
     * Sets the value of the batchReport property.
     *
     * @param value allowed object is
     *              {@link BatchReport }
     */
    public void setBatchReport(BatchReport value) {
        this.batchReport = value;
    }

}
