//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Beneficiary complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Beneficiary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="accName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="accNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="branchCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bankName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bankRegNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Beneficiary", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema")
public class Beneficiary {

    @XmlAttribute(name = "accName")
    protected String accName;
    @XmlAttribute(name = "accNo")
    protected String accNo;
    @XmlAttribute(name = "branchCode")
    protected String branchCode;
    @XmlAttribute(name = "bankName")
    protected String bankName;
    @XmlAttribute(name = "bankRegNo")
    protected String bankRegNo;

    /**
     * Gets the value of the accName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccName() {
        return accName;
    }

    /**
     * Sets the value of the accName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccName(String value) {
        this.accName = value;
    }

    /**
     * Gets the value of the accNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * Sets the value of the accNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccNo(String value) {
        this.accNo = value;
    }

    /**
     * Gets the value of the branchCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the bankRegNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankRegNo() {
        return bankRegNo;
    }

    /**
     * Sets the value of the bankRegNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankRegNo(String value) {
        this.bankRegNo = value;
    }

}
