//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessRuleEx complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BusinessRuleEx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Fault"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessRuleEx")
@XmlSeeAlso({
        RequestAuthorisationEx.class,
        MSNOCheckDigitEx.class,
        SGCAuthorisationEx.class,
        LatestKRNEx.class,
        FBEEx.class,
        BlockedMeterEx.class,
        UpdateMtrKeySameEx.class,
        VendorCreditEx.class,
        ClientIDAuthorisationEx.class,
        ConfirmCustomerEx.class,
        CancelEx.class,
        CheckBatchTotalEx.class,
        DebtEx.class,
        EndBatchEx.class,
        InsufficientMeterDataEx.class,
        ReprintDepositSlipEx.class,
        ReprintEndBatchEx.class,
        ReprintEx.class,
        RequireMeterCardEx.class,
        StartBatchEx.class,
        ServiceChrgEx.class,
        UnknownMeterEx.class,
        UnknownMeterUpdateMtrKeyEx.class,
        STSDataEx.class,
        VerifyTokenEx.class,
        UnknownMeterFBEEx.class,
        DuplicateMsgIDEx.class,
        GracePurchaseEx.class,
        OtherDataEx.class,
        MeterDataMisMatchEx.class,
        IndeterminantLastResponseEx.class,
        AccNumMeterLinkEx.class,
        AccNumEx.class,
        EngParameterEx.class,
        AccTypeEx.class
})
public class BusinessRuleEx
        extends Fault {


}
