//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancelPendingReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CancelPendingReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CancelVendReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="adviceReqMsgID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MsgID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelPendingReq", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "adviceReqMsgID"
})
public class CancelPendingReq
        extends CancelVendReq {

    protected MsgID adviceReqMsgID;

    /**
     * Gets the value of the adviceReqMsgID property.
     *
     * @return possible object is
     * {@link MsgID }
     */
    public MsgID getAdviceReqMsgID() {
        return adviceReqMsgID;
    }

    /**
     * Sets the value of the adviceReqMsgID property.
     *
     * @param value allowed object is
     *              {@link MsgID }
     */
    public void setAdviceReqMsgID(MsgID value) {
        this.adviceReqMsgID = value;
    }

}
