//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for CancelVendResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CancelVendResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseVendResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="origTx" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CreditVendTx" minOccurs="0"/&gt;
 *         &lt;element name="CisVendingServerDetail" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CisVendingServerDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="cancelRefNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelVendResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "origTx",
        "cisVendingServerDetail"
})
@XmlSeeAlso({
        CancelPendingResp.class
})
public class CancelVendResp
        extends BaseVendResp {

    protected CreditVendTx origTx;
    @XmlElement(name = "CisVendingServerDetail")
    protected CisVendingServerDetail cisVendingServerDetail;
    @XmlAttribute(name = "cancelRefNo")
    protected String cancelRefNo;

    /**
     * Gets the value of the origTx property.
     *
     * @return possible object is
     * {@link CreditVendTx }
     */
    public CreditVendTx getOrigTx() {
        return origTx;
    }

    /**
     * Sets the value of the origTx property.
     *
     * @param value allowed object is
     *              {@link CreditVendTx }
     */
    public void setOrigTx(CreditVendTx value) {
        this.origTx = value;
    }

    /**
     * Gets the value of the cisVendingServerDetail property.
     *
     * @return possible object is
     * {@link CisVendingServerDetail }
     */
    public CisVendingServerDetail getCisVendingServerDetail() {
        return cisVendingServerDetail;
    }

    /**
     * Sets the value of the cisVendingServerDetail property.
     *
     * @param value allowed object is
     *              {@link CisVendingServerDetail }
     */
    public void setCisVendingServerDetail(CisVendingServerDetail value) {
        this.cisVendingServerDetail = value;
    }

    /**
     * Gets the value of the cancelRefNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCancelRefNo() {
        return cancelRefNo;
    }

    /**
     * Sets the value of the cancelRefNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCancelRefNo(String value) {
        this.cancelRefNo = value;
    }

}
