//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for CancelVendReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CancelVendReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseVendReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CDUID" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}EANDeviceID" minOccurs="0"/&gt;
 *         &lt;element name="CancellationReasonCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="token" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}STS1Token" minOccurs="0"/&gt;
 *         &lt;element name="DocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AutoCancel" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="OriginalUniqueNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelVendReq", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "transactionNumber",
        "cduid",
        "cancellationReasonCode",
        "token",
        "documentNumber",
        "autoCancel",
        "originalUniqueNumber"
})
@XmlSeeAlso({
        CancelPendingReq.class
})
public class CancelVendReq
        extends BaseVendReq {

    @XmlElement(name = "TransactionNumber")
    protected String transactionNumber;
    @XmlElement(name = "CDUID")
    protected EANDeviceID cduid;
    @XmlElement(name = "CancellationReasonCode")
    protected String cancellationReasonCode;
    protected STS1Token token;
    @XmlElement(name = "DocumentNumber")
    protected String documentNumber;
    @XmlElement(name = "AutoCancel")
    protected boolean autoCancel;
    @XmlElement(name = "OriginalUniqueNumber")
    protected String originalUniqueNumber;

    /**
     * Gets the value of the transactionNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * Sets the value of the transactionNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionNumber(String value) {
        this.transactionNumber = value;
    }

    /**
     * Gets the value of the cduid property.
     *
     * @return possible object is
     * {@link EANDeviceID }
     */
    public EANDeviceID getCDUID() {
        return cduid;
    }

    /**
     * Sets the value of the cduid property.
     *
     * @param value allowed object is
     *              {@link EANDeviceID }
     */
    public void setCDUID(EANDeviceID value) {
        this.cduid = value;
    }

    /**
     * Gets the value of the cancellationReasonCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCancellationReasonCode() {
        return cancellationReasonCode;
    }

    /**
     * Sets the value of the cancellationReasonCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCancellationReasonCode(String value) {
        this.cancellationReasonCode = value;
    }

    /**
     * Gets the value of the token property.
     *
     * @return possible object is
     * {@link STS1Token }
     */
    public STS1Token getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     *
     * @param value allowed object is
     *              {@link STS1Token }
     */
    public void setToken(STS1Token value) {
        this.token = value;
    }

    /**
     * Gets the value of the documentNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the autoCancel property.
     */
    public boolean isAutoCancel() {
        return autoCancel;
    }

    /**
     * Sets the value of the autoCancel property.
     */
    public void setAutoCancel(boolean value) {
        this.autoCancel = value;
    }

    /**
     * Gets the value of the originalUniqueNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOriginalUniqueNumber() {
        return originalUniqueNumber;
    }

    /**
     * Sets the value of the originalUniqueNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOriginalUniqueNumber(String value) {
        this.originalUniqueNumber = value;
    }

}
