//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Card complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Card"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}PayType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cardAmt" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="accHolderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cvNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clearingHouse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Card", propOrder = {
        "cardAmt",
        "accHolderName",
        "pan",
        "expDate",
        "cvNum",
        "clearingHouse"
})
@XmlSeeAlso({
        DebitCard.class,
        CreditCard.class
})
public abstract class Card
        extends PayType {

    protected Currency cardAmt;
    protected String accHolderName;
    protected String pan;
    protected String expDate;
    protected String cvNum;
    protected String clearingHouse;

    /**
     * Gets the value of the cardAmt property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getCardAmt() {
        return cardAmt;
    }

    /**
     * Sets the value of the cardAmt property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setCardAmt(Currency value) {
        this.cardAmt = value;
    }

    /**
     * Gets the value of the accHolderName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccHolderName() {
        return accHolderName;
    }

    /**
     * Sets the value of the accHolderName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccHolderName(String value) {
        this.accHolderName = value;
    }

    /**
     * Gets the value of the pan property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPan() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPan(String value) {
        this.pan = value;
    }

    /**
     * Gets the value of the expDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExpDate() {
        return expDate;
    }

    /**
     * Sets the value of the expDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExpDate(String value) {
        this.expDate = value;
    }

    /**
     * Gets the value of the cvNum property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCvNum() {
        return cvNum;
    }

    /**
     * Sets the value of the cvNum property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCvNum(String value) {
        this.cvNum = value;
    }

    /**
     * Gets the value of the clearingHouse property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClearingHouse() {
        return clearingHouse;
    }

    /**
     * Sets the value of the clearingHouse property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClearingHouse(String value) {
        this.clearingHouse = value;
    }

}
