//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CisVendingServerDetail complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CisVendingServerDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="AccountType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DtName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DtNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OrgNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OrgName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CisVendingServerDetail", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema")
public class CisVendingServerDetail {

    @XmlAttribute(name = "AccountType")
    protected String accountType;
    @XmlAttribute(name = "DtName")
    protected String dtName;
    @XmlAttribute(name = "DtNumber")
    protected String dtNumber;
    @XmlAttribute(name = "OrgNo")
    protected String orgNo;
    @XmlAttribute(name = "OrgName")
    protected String orgName;

    /**
     * Gets the value of the accountType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the dtName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDtName() {
        return dtName;
    }

    /**
     * Sets the value of the dtName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDtName(String value) {
        this.dtName = value;
    }

    /**
     * Gets the value of the dtNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDtNumber() {
        return dtNumber;
    }

    /**
     * Sets the value of the dtNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDtNumber(String value) {
        this.dtNumber = value;
    }

    /**
     * Gets the value of the orgNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * Sets the value of the orgNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrgNo(String value) {
        this.orgNo = value;
    }

    /**
     * Gets the value of the orgName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * Sets the value of the orgName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrgName(String value) {
        this.orgName = value;
    }

}
