//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientStatus complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ClientStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="availCredit" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="batchStatus" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BatchStatus" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientStatus", propOrder = {
        "availCredit",
        "batchStatus"
})
public class ClientStatus {

    protected Currency availCredit;
    protected BatchStatus batchStatus;

    /**
     * Gets the value of the availCredit property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getAvailCredit() {
        return availCredit;
    }

    /**
     * Sets the value of the availCredit property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setAvailCredit(Currency value) {
        this.availCredit = value;
    }

    /**
     * Gets the value of the batchStatus property.
     *
     * @return possible object is
     * {@link BatchStatus }
     */
    public BatchStatus getBatchStatus() {
        return batchStatus;
    }

    /**
     * Sets the value of the batchStatus property.
     *
     * @param value allowed object is
     *              {@link BatchStatus }
     */
    public void setBatchStatus(BatchStatus value) {
        this.batchStatus = value;
    }

}
