//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for CmftReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CmftReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseVendReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CmftType" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}TokenTypes"/&gt;
 *         &lt;element name="SGC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KeyRevNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TarrifIndex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GeneralPurposeValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CmftReq", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "cmftType",
        "sgc",
        "keyRevNo",
        "tarrifIndex",
        "generalPurposeValue"
})
public class CmftReq
        extends BaseVendReq {

    @XmlElement(name = "CmftType", required = true)
    @XmlSchemaType(name = "string")
    protected TokenTypes cmftType;
    @XmlElement(name = "SGC")
    protected String sgc;
    @XmlElement(name = "KeyRevNo")
    protected String keyRevNo;
    @XmlElement(name = "TarrifIndex")
    protected String tarrifIndex;
    @XmlElement(name = "GeneralPurposeValue")
    protected String generalPurposeValue;

    /**
     * Gets the value of the cmftType property.
     *
     * @return possible object is
     * {@link TokenTypes }
     */
    public TokenTypes getCmftType() {
        return cmftType;
    }

    /**
     * Sets the value of the cmftType property.
     *
     * @param value allowed object is
     *              {@link TokenTypes }
     */
    public void setCmftType(TokenTypes value) {
        this.cmftType = value;
    }

    /**
     * Gets the value of the sgc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSGC() {
        return sgc;
    }

    /**
     * Sets the value of the sgc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSGC(String value) {
        this.sgc = value;
    }

    /**
     * Gets the value of the keyRevNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKeyRevNo() {
        return keyRevNo;
    }

    /**
     * Sets the value of the keyRevNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKeyRevNo(String value) {
        this.keyRevNo = value;
    }

    /**
     * Gets the value of the tarrifIndex property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTarrifIndex() {
        return tarrifIndex;
    }

    /**
     * Sets the value of the tarrifIndex property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTarrifIndex(String value) {
        this.tarrifIndex = value;
    }

    /**
     * Gets the value of the generalPurposeValue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGeneralPurposeValue() {
        return generalPurposeValue;
    }

    /**
     * Sets the value of the generalPurposeValue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGeneralPurposeValue(String value) {
        this.generalPurposeValue = value;
    }

}
