//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfirmCustResult complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConfirmCustResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="custVendDetail" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CustVendDetail" minOccurs="0"/&gt;
 *         &lt;element name="custVendConfig" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CustVendConfig" minOccurs="0"/&gt;
 *         &lt;element name="meterDetail" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterDetail" minOccurs="0"/&gt;
 *         &lt;element name="custAccountDetail" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CustAccountDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfirmCustResult", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "custVendDetail",
        "custVendConfig",
        "meterDetail",
        "custAccountDetail"
})
public class ConfirmCustResult {

    protected CustVendDetail custVendDetail;
    protected CustVendConfig custVendConfig;
    protected MeterDetail meterDetail;
    protected CustAccountDetail custAccountDetail;

    /**
     * Gets the value of the custVendDetail property.
     *
     * @return possible object is
     * {@link CustVendDetail }
     */
    public CustVendDetail getCustVendDetail() {
        return custVendDetail;
    }

    /**
     * Sets the value of the custVendDetail property.
     *
     * @param value allowed object is
     *              {@link CustVendDetail }
     */
    public void setCustVendDetail(CustVendDetail value) {
        this.custVendDetail = value;
    }

    /**
     * Gets the value of the custVendConfig property.
     *
     * @return possible object is
     * {@link CustVendConfig }
     */
    public CustVendConfig getCustVendConfig() {
        return custVendConfig;
    }

    /**
     * Sets the value of the custVendConfig property.
     *
     * @param value allowed object is
     *              {@link CustVendConfig }
     */
    public void setCustVendConfig(CustVendConfig value) {
        this.custVendConfig = value;
    }

    /**
     * Gets the value of the meterDetail property.
     *
     * @return possible object is
     * {@link MeterDetail }
     */
    public MeterDetail getMeterDetail() {
        return meterDetail;
    }

    /**
     * Sets the value of the meterDetail property.
     *
     * @param value allowed object is
     *              {@link MeterDetail }
     */
    public void setMeterDetail(MeterDetail value) {
        this.meterDetail = value;
    }

    /**
     * Gets the value of the custAccountDetail property.
     *
     * @return possible object is
     * {@link CustAccountDetail }
     */
    public CustAccountDetail getCustAccountDetail() {
        return custAccountDetail;
    }

    /**
     * Sets the value of the custAccountDetail property.
     *
     * @param value allowed object is
     *              {@link CustAccountDetail }
     */
    public void setCustAccountDetail(CustAccountDetail value) {
        this.custAccountDetail = value;
    }

}
