//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfirmMeterResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConfirmMeterResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="confirmMeterResult" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}ConfirmMeterResult" minOccurs="0"/&gt;
 *         &lt;element name="CustomerNotes" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}CustomerNotes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfirmMeterResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "confirmMeterResult",
        "customerNotes"
})
public class ConfirmMeterResp
        extends BaseResp {

    protected ConfirmMeterResult confirmMeterResult;
    @XmlElement(name = "CustomerNotes")
    protected CustomerNotes customerNotes;

    /**
     * Gets the value of the confirmMeterResult property.
     *
     * @return possible object is
     * {@link ConfirmMeterResult }
     */
    public ConfirmMeterResult getConfirmMeterResult() {
        return confirmMeterResult;
    }

    /**
     * Sets the value of the confirmMeterResult property.
     *
     * @param value allowed object is
     *              {@link ConfirmMeterResult }
     */
    public void setConfirmMeterResult(ConfirmMeterResult value) {
        this.confirmMeterResult = value;
    }

    /**
     * Gets the value of the customerNotes property.
     *
     * @return possible object is
     * {@link CustomerNotes }
     */
    public CustomerNotes getCustomerNotes() {
        return customerNotes;
    }

    /**
     * Sets the value of the customerNotes property.
     *
     * @param value allowed object is
     *              {@link CustomerNotes }
     */
    public void setCustomerNotes(CustomerNotes value) {
        this.customerNotes = value;
    }

}
