//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfirmationAdviceReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConfirmationAdviceReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}AdviceReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="payType" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}PayType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfirmationAdviceReq", propOrder = {
        "payType"
})
public class ConfirmationAdviceReq
        extends AdviceReq {

    protected PayType payType;

    /**
     * Gets the value of the payType property.
     *
     * @return possible object is
     * {@link PayType }
     */
    public PayType getPayType() {
        return payType;
    }

    /**
     * Sets the value of the payType property.
     *
     * @param value allowed object is
     *              {@link PayType }
     */
    public void setPayType(PayType value) {
        this.payType = value;
    }

}
