//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditTokenIssue complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreditTokenIssue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterSpecificTokenIssue"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="units" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Units" minOccurs="0"/&gt;
 *         &lt;element name="resource" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Resource" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditTokenIssue", propOrder = {
        "units",
        "resource"
})
@XmlSeeAlso({
        SaleCredTokenIssue.class,
        FreeCredTokenIssue.class,
        MCTCredTokenIssue.class,
        FBECredTokenIssue.class,
        OverRecCredTokenIssue.class
})
public class CreditTokenIssue
        extends MeterSpecificTokenIssue {

    protected Units units;
    protected Resource resource;

    /**
     * Gets the value of the units property.
     *
     * @return possible object is
     * {@link Units }
     */
    public Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     *
     * @param value allowed object is
     *              {@link Units }
     */
    public void setUnits(Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the resource property.
     *
     * @return possible object is
     * {@link Resource }
     */
    public Resource getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     *
     * @param value allowed object is
     *              {@link Resource }
     */
    public void setResource(Resource value) {
        this.resource = value;
    }

}
