//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditVendTx complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreditVendTx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}Tx"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="creditTokenIssue" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CreditTokenIssue" minOccurs="0"/&gt;
 *         &lt;element name="tariff" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Tariff" minOccurs="0"/&gt;
 *         &lt;element name="tariffBreakdown" type="{http://www.conlog.co.za/xmlvend/base-ext/2.1.1/schema}TariffBreakdown" minOccurs="0"/&gt;
 *         &lt;element name="tariffBenefaction" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}TariffBenefaction" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditVendTx", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "creditTokenIssue",
        "tariff",
        "tariffBreakdown",
        "tariffBenefaction"
})
public class CreditVendTx
        extends Tx {

    protected CreditTokenIssue creditTokenIssue;
    protected Tariff tariff;
    protected TariffBreakdown tariffBreakdown;
    protected TariffBenefaction tariffBenefaction;

    /**
     * Gets the value of the creditTokenIssue property.
     *
     * @return possible object is
     * {@link CreditTokenIssue }
     */
    public CreditTokenIssue getCreditTokenIssue() {
        return creditTokenIssue;
    }

    /**
     * Sets the value of the creditTokenIssue property.
     *
     * @param value allowed object is
     *              {@link CreditTokenIssue }
     */
    public void setCreditTokenIssue(CreditTokenIssue value) {
        this.creditTokenIssue = value;
    }

    /**
     * Gets the value of the tariff property.
     *
     * @return possible object is
     * {@link Tariff }
     */
    public Tariff getTariff() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     *
     * @param value allowed object is
     *              {@link Tariff }
     */
    public void setTariff(Tariff value) {
        this.tariff = value;
    }

    /**
     * Gets the value of the tariffBreakdown property.
     *
     * @return possible object is
     * {@link TariffBreakdown }
     */
    public TariffBreakdown getTariffBreakdown() {
        return tariffBreakdown;
    }

    /**
     * Sets the value of the tariffBreakdown property.
     *
     * @param value allowed object is
     *              {@link TariffBreakdown }
     */
    public void setTariffBreakdown(TariffBreakdown value) {
        this.tariffBreakdown = value;
    }

    /**
     * Gets the value of the tariffBenefaction property.
     *
     * @return possible object is
     * {@link TariffBenefaction }
     */
    public TariffBenefaction getTariffBenefaction() {
        return tariffBenefaction;
    }

    /**
     * Sets the value of the tariffBenefaction property.
     *
     * @param value allowed object is
     *              {@link TariffBenefaction }
     */
    public void setTariffBenefaction(TariffBenefaction value) {
        this.tariffBenefaction = value;
    }

}
