//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditTokenSubClassType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="CreditTokenSubClassType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Electricity Token"/&gt;
 *     &lt;enumeration value="Water Token"/&gt;
 *     &lt;enumeration value="Gas Token"/&gt;
 *     &lt;enumeration value="Connection time Token"/&gt;
 *     &lt;enumeration value="Currency Token"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "CreditTokenSubClassType")
@XmlEnum
public enum CreditTokenSubClassType {

    @XmlEnumValue("Electricity Token")
    ELECTRICITY_TOKEN("Electricity Token"),
    @XmlEnumValue("Water Token")
    WATER_TOKEN("Water Token"),
    @XmlEnumValue("Gas Token")
    GAS_TOKEN("Gas Token"),
    @XmlEnumValue("Connection time Token")
    CONNECTION_TIME_TOKEN("Connection time Token"),
    @XmlEnumValue("Currency Token")
    CURRENCY_TOKEN("Currency Token");
    private final String value;

    CreditTokenSubClassType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CreditTokenSubClassType fromValue(String v) {
        for (CreditTokenSubClassType c : CreditTokenSubClassType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
