//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for CreditVendResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreditVendResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseVendResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="creditVendReceipt" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CreditVendReceipt" minOccurs="0"/&gt;
 *         &lt;element name="CisVendingServerDetail" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CisVendingServerDetail" minOccurs="0"/&gt;
 *         &lt;element name="CustomerNotes" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}CustomerNotes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditVendResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "creditVendReceipt",
        "cisVendingServerDetail",
        "customerNotes"
})
@XmlSeeAlso({
        FBEResp.class,
        TrialCreditVendResp.class,
        FreeIssueResp.class,
        TrialImpulseVendResp.class,
        ImpulseVendResp.class
})
public class CreditVendResp
        extends BaseVendResp {

    protected CreditVendReceipt creditVendReceipt;
    @XmlElement(name = "CisVendingServerDetail")
    protected CisVendingServerDetail cisVendingServerDetail;
    @XmlElement(name = "CustomerNotes")
    protected CustomerNotes customerNotes;

    /**
     * Gets the value of the creditVendReceipt property.
     *
     * @return possible object is
     * {@link CreditVendReceipt }
     */
    public CreditVendReceipt getCreditVendReceipt() {
        return creditVendReceipt;
    }

    /**
     * Sets the value of the creditVendReceipt property.
     *
     * @param value allowed object is
     *              {@link CreditVendReceipt }
     */
    public void setCreditVendReceipt(CreditVendReceipt value) {
        this.creditVendReceipt = value;
    }

    /**
     * Gets the value of the cisVendingServerDetail property.
     *
     * @return possible object is
     * {@link CisVendingServerDetail }
     */
    public CisVendingServerDetail getCisVendingServerDetail() {
        return cisVendingServerDetail;
    }

    /**
     * Sets the value of the cisVendingServerDetail property.
     *
     * @param value allowed object is
     *              {@link CisVendingServerDetail }
     */
    public void setCisVendingServerDetail(CisVendingServerDetail value) {
        this.cisVendingServerDetail = value;
    }

    /**
     * Gets the value of the customerNotes property.
     *
     * @return possible object is
     * {@link CustomerNotes }
     */
    public CustomerNotes getCustomerNotes() {
        return customerNotes;
    }

    /**
     * Sets the value of the customerNotes property.
     *
     * @param value allowed object is
     *              {@link CustomerNotes }
     */
    public void setCustomerNotes(CustomerNotes value) {
        this.customerNotes = value;
    }

}
