//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditTransferDetail complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreditTransferDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oldMSNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="refNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditTransferDetail", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "oldMSNO",
        "refNo"
})
public class CreditTransferDetail {

    protected String oldMSNO;
    protected String refNo;

    /**
     * Gets the value of the oldMSNO property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOldMSNO() {
        return oldMSNO;
    }

    /**
     * Sets the value of the oldMSNO property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOldMSNO(String value) {
        this.oldMSNO = value;
    }

    /**
     * Gets the value of the refNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRefNo() {
        return refNo;
    }

    /**
     * Sets the value of the refNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRefNo(String value) {
        this.refNo = value;
    }

}
