//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;


/**
 * <p>Java class for CustVendDetail complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustVendDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CustDetail"&gt;
 *       &lt;attribute name="utilityType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taxReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="daysLastPurchase" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustVendDetail")
public class CustVendDetail
        extends CustDetail {

    @XmlAttribute(name = "utilityType")
    protected String utilityType;
    @XmlAttribute(name = "taxReferenceNo")
    protected String taxReferenceNo;
    @XmlAttribute(name = "daysLastPurchase")
    protected BigInteger daysLastPurchase;

    /**
     * Gets the value of the utilityType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUtilityType() {
        return utilityType;
    }

    /**
     * Sets the value of the utilityType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUtilityType(String value) {
        this.utilityType = value;
    }

    /**
     * Gets the value of the taxReferenceNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTaxReferenceNo() {
        return taxReferenceNo;
    }

    /**
     * Sets the value of the taxReferenceNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTaxReferenceNo(String value) {
        this.taxReferenceNo = value;
    }

    /**
     * Gets the value of the daysLastPurchase property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getDaysLastPurchase() {
        return daysLastPurchase;
    }

    /**
     * Sets the value of the daysLastPurchase property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setDaysLastPurchase(BigInteger value) {
        this.daysLastPurchase = value;
    }

}
