//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustReportFaultReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustReportFaultReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="custDetail" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CustDetail" minOccurs="0"/&gt;
 *         &lt;element name="custFaultReport" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}CustFaultReport" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustReportFaultReq", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "custDetail",
        "custFaultReport"
})
public class CustReportFaultReq
        extends BaseReq {

    protected CustDetail custDetail;
    protected CustFaultReport custFaultReport;

    /**
     * Gets the value of the custDetail property.
     *
     * @return possible object is
     * {@link CustDetail }
     */
    public CustDetail getCustDetail() {
        return custDetail;
    }

    /**
     * Sets the value of the custDetail property.
     *
     * @param value allowed object is
     *              {@link CustDetail }
     */
    public void setCustDetail(CustDetail value) {
        this.custDetail = value;
    }

    /**
     * Gets the value of the custFaultReport property.
     *
     * @return possible object is
     * {@link CustFaultReport }
     */
    public CustFaultReport getCustFaultReport() {
        return custFaultReport;
    }

    /**
     * Sets the value of the custFaultReport property.
     *
     * @param value allowed object is
     *              {@link CustFaultReport }
     */
    public void setCustFaultReport(CustFaultReport value) {
        this.custFaultReport = value;
    }

}
