//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustReportFaultResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustReportFaultResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="custFaultLog" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}CustFaultLog" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustReportFaultResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "custFaultLog"
})
public class CustReportFaultResp
        extends BaseResp {

    protected CustFaultLog custFaultLog;

    /**
     * Gets the value of the custFaultLog property.
     *
     * @return possible object is
     * {@link CustFaultLog }
     */
    public CustFaultLog getCustFaultLog() {
        return custFaultLog;
    }

    /**
     * Sets the value of the custFaultLog property.
     *
     * @param value allowed object is
     *              {@link CustFaultLog }
     */
    public void setCustFaultLog(CustFaultLog value) {
        this.custFaultLog = value;
    }

}
