//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DepositCreditUpdate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DepositCreditUpdate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.eskom.co.za/xmlvend/revenue-ext/2.1/schema}CredUpdate"&gt;
 *       &lt;attribute name="depositRefNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="depositDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepositCreditUpdate", namespace = "http://www.eskom.co.za/xmlvend/revenue-ext/2.1/schema")
public class DepositCreditUpdate
        extends CredUpdate {

    @XmlAttribute(name = "depositRefNo")
    protected String depositRefNo;
    @XmlAttribute(name = "depositDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar depositDate;

    /**
     * Gets the value of the depositRefNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDepositRefNo() {
        return depositRefNo;
    }

    /**
     * Sets the value of the depositRefNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDepositRefNo(String value) {
        this.depositRefNo = value;
    }

    /**
     * Gets the value of the depositDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDepositDate() {
        return depositDate;
    }

    /**
     * Sets the value of the depositDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDepositDate(XMLGregorianCalendar value) {
        this.depositDate = value;
    }

}
