//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispVerResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DispVerResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}NonMeterSpecificEngResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dispVer" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}DispVerTokenIssue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispVerResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "dispVer"
})
public class DispVerResp
        extends NonMeterSpecificEngResp {

    protected DispVerTokenIssue dispVer;

    /**
     * Gets the value of the dispVer property.
     *
     * @return possible object is
     * {@link DispVerTokenIssue }
     */
    public DispVerTokenIssue getDispVer() {
        return dispVer;
    }

    /**
     * Sets the value of the dispVer property.
     *
     * @param value allowed object is
     *              {@link DispVerTokenIssue }
     */
    public void setDispVer(DispVerTokenIssue value) {
        this.dispVer = value;
    }

}
