//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Eft complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Eft"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}PayType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="eftAmt" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="accHolderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accHolderIDNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="branchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="depositReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Eft", propOrder = {
        "eftAmt",
        "accHolderName",
        "accHolderIDNo",
        "accNo",
        "bankName",
        "branchCode",
        "depositReferenceNumber"
})
public class Eft
        extends PayType {

    protected Currency eftAmt;
    protected String accHolderName;
    protected String accHolderIDNo;
    protected String accNo;
    protected String bankName;
    protected String branchCode;
    protected String depositReferenceNumber;

    /**
     * Gets the value of the eftAmt property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getEftAmt() {
        return eftAmt;
    }

    /**
     * Sets the value of the eftAmt property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setEftAmt(Currency value) {
        this.eftAmt = value;
    }

    /**
     * Gets the value of the accHolderName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccHolderName() {
        return accHolderName;
    }

    /**
     * Sets the value of the accHolderName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccHolderName(String value) {
        this.accHolderName = value;
    }

    /**
     * Gets the value of the accHolderIDNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccHolderIDNo() {
        return accHolderIDNo;
    }

    /**
     * Sets the value of the accHolderIDNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccHolderIDNo(String value) {
        this.accHolderIDNo = value;
    }

    /**
     * Gets the value of the accNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * Sets the value of the accNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccNo(String value) {
        this.accNo = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the branchCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the depositReferenceNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDepositReferenceNumber() {
        return depositReferenceNumber;
    }

    /**
     * Sets the value of the depositReferenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDepositReferenceNumber(String value) {
        this.depositReferenceNumber = value;
    }

}
