//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;


/**
 * <p>Java class for ExchangeRate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ExchangeRate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="BaseCurrency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ExchangeCurrency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ExchangRate" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangeRate", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema")
public class ExchangeRate {

    @XmlAttribute(name = "BaseCurrency")
    protected String baseCurrency;
    @XmlAttribute(name = "ExchangeCurrency")
    protected String exchangeCurrency;
    @XmlAttribute(name = "ExchangRate", required = true)
    protected BigDecimal exchangRate;

    /**
     * Gets the value of the baseCurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBaseCurrency() {
        return baseCurrency;
    }

    /**
     * Sets the value of the baseCurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBaseCurrency(String value) {
        this.baseCurrency = value;
    }

    /**
     * Gets the value of the exchangeCurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExchangeCurrency() {
        return exchangeCurrency;
    }

    /**
     * Sets the value of the exchangeCurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExchangeCurrency(String value) {
        this.exchangeCurrency = value;
    }

    /**
     * Gets the value of the exchangRate property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getExchangRate() {
        return exchangRate;
    }

    /**
     * Sets the value of the exchangRate property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setExchangRate(BigDecimal value) {
        this.exchangRate = value;
    }

}
