//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KCTData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="KCTData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="fromSGC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fromKRN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fromTI" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="toSGC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="toKRN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="toTI" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KCTData")
public class KCTData {

    @XmlAttribute(name = "fromSGC")
    protected String fromSGC;
    @XmlAttribute(name = "fromKRN")
    protected String fromKRN;
    @XmlAttribute(name = "fromTI")
    protected String fromTI;
    @XmlAttribute(name = "toSGC")
    protected String toSGC;
    @XmlAttribute(name = "toKRN")
    protected String toKRN;
    @XmlAttribute(name = "toTI")
    protected String toTI;

    /**
     * Gets the value of the fromSGC property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFromSGC() {
        return fromSGC;
    }

    /**
     * Sets the value of the fromSGC property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFromSGC(String value) {
        this.fromSGC = value;
    }

    /**
     * Gets the value of the fromKRN property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFromKRN() {
        return fromKRN;
    }

    /**
     * Sets the value of the fromKRN property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFromKRN(String value) {
        this.fromKRN = value;
    }

    /**
     * Gets the value of the fromTI property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFromTI() {
        return fromTI;
    }

    /**
     * Sets the value of the fromTI property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFromTI(String value) {
        this.fromTI = value;
    }

    /**
     * Gets the value of the toSGC property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getToSGC() {
        return toSGC;
    }

    /**
     * Sets the value of the toSGC property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setToSGC(String value) {
        this.toSGC = value;
    }

    /**
     * Gets the value of the toKRN property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getToKRN() {
        return toKRN;
    }

    /**
     * Sets the value of the toKRN property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setToKRN(String value) {
        this.toKRN = value;
    }

    /**
     * Gets the value of the toTI property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getToTI() {
        return toTI;
    }

    /**
     * Sets the value of the toTI property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setToTI(String value) {
        this.toTI = value;
    }

}
