//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;


/**
 * <p>Java class for MakeMerchantDepositReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MakeMerchantDepositReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountHolderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AmountDeposited" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateDeposited" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DepositReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BankBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MakeMerchantDepositReq", propOrder = {
        "accountHolderName",
        "accountNo",
        "amountDeposited",
        "bankName",
        "dateDeposited",
        "depositReferenceNumber",
        "notes",
        "bankBranchCode"
})
public class MakeMerchantDepositReq
        extends BaseReq {

    @XmlElement(name = "AccountHolderName")
    protected String accountHolderName;
    @XmlElement(name = "AccountNo")
    protected String accountNo;
    @XmlElement(name = "AmountDeposited", required = true)
    protected BigDecimal amountDeposited;
    @XmlElement(name = "BankName")
    protected String bankName;
    @XmlElement(name = "DateDeposited")
    protected String dateDeposited;
    @XmlElement(name = "DepositReferenceNumber")
    protected String depositReferenceNumber;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "BankBranchCode")
    protected String bankBranchCode;

    /**
     * Gets the value of the accountHolderName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountHolderName() {
        return accountHolderName;
    }

    /**
     * Sets the value of the accountHolderName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountHolderName(String value) {
        this.accountHolderName = value;
    }

    /**
     * Gets the value of the accountNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the amountDeposited property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getAmountDeposited() {
        return amountDeposited;
    }

    /**
     * Sets the value of the amountDeposited property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAmountDeposited(BigDecimal value) {
        this.amountDeposited = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the dateDeposited property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateDeposited() {
        return dateDeposited;
    }

    /**
     * Sets the value of the dateDeposited property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateDeposited(String value) {
        this.dateDeposited = value;
    }

    /**
     * Gets the value of the depositReferenceNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDepositReferenceNumber() {
        return depositReferenceNumber;
    }

    /**
     * Sets the value of the depositReferenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDepositReferenceNumber(String value) {
        this.depositReferenceNumber = value;
    }

    /**
     * Gets the value of the notes property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the bankBranchCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankBranchCode() {
        return bankBranchCode;
    }

    /**
     * Sets the value of the bankBranchCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankBranchCode(String value) {
        this.bankBranchCode = value;
    }

}
