//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MenuAccessResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MenuAccessResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}NonMeterSpecificEngResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="menuAccess" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}MenuAccessTokenIssue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MenuAccessResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "menuAccess"
})
public class MenuAccessResp
        extends NonMeterSpecificEngResp {

    protected MenuAccessTokenIssue menuAccess;

    /**
     * Gets the value of the menuAccess property.
     *
     * @return possible object is
     * {@link MenuAccessTokenIssue }
     */
    public MenuAccessTokenIssue getMenuAccess() {
        return menuAccess;
    }

    /**
     * Sets the value of the menuAccess property.
     *
     * @param value allowed object is
     *              {@link MenuAccessTokenIssue }
     */
    public void setMenuAccess(MenuAccessTokenIssue value) {
        this.menuAccess = value;
    }

}
