//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeterFaultReport complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeterFaultReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}CustFaultReport"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="meterInfo" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}VendIDMethod" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeterFaultReport", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "meterInfo"
})
@XmlSeeAlso({
        DeviceFault.class,
        DataFault.class
})
public class MeterFaultReport
        extends CustFaultReport {

    protected VendIDMethod meterInfo;

    /**
     * Gets the value of the meterInfo property.
     *
     * @return possible object is
     * {@link VendIDMethod }
     */
    public VendIDMethod getMeterInfo() {
        return meterInfo;
    }

    /**
     * Sets the value of the meterInfo property.
     *
     * @param value allowed object is
     *              {@link VendIDMethod }
     */
    public void setMeterInfo(VendIDMethod value) {
        this.meterInfo = value;
    }

}
