//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeterCreditTransferResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeterCreditTransferResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseVendResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="creditTransferDetail" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CreditTransferDetail" minOccurs="0"/&gt;
 *         &lt;element name="creditTransferTx" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CreditVendTx" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeterCreditTransferResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "creditTransferDetail",
        "creditTransferTx"
})
public class MeterCreditTransferResp
        extends BaseVendResp {

    protected CreditTransferDetail creditTransferDetail;
    protected CreditVendTx creditTransferTx;

    /**
     * Gets the value of the creditTransferDetail property.
     *
     * @return possible object is
     * {@link CreditTransferDetail }
     */
    public CreditTransferDetail getCreditTransferDetail() {
        return creditTransferDetail;
    }

    /**
     * Sets the value of the creditTransferDetail property.
     *
     * @param value allowed object is
     *              {@link CreditTransferDetail }
     */
    public void setCreditTransferDetail(CreditTransferDetail value) {
        this.creditTransferDetail = value;
    }

    /**
     * Gets the value of the creditTransferTx property.
     *
     * @return possible object is
     * {@link CreditVendTx }
     */
    public CreditVendTx getCreditTransferTx() {
        return creditTransferTx;
    }

    /**
     * Sets the value of the creditTransferTx property.
     *
     * @param value allowed object is
     *              {@link CreditVendTx }
     */
    public void setCreditTransferTx(CreditVendTx value) {
        this.creditTransferTx = value;
    }

}
