//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeterType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="at" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeterType")
public class MeterType {

    @XmlAttribute(name = "at")
    protected String at;
    @XmlAttribute(name = "tt")
    protected String tt;

    /**
     * Gets the value of the at property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAt() {
        return at;
    }

    /**
     * Sets the value of the at property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAt(String value) {
        this.at = value;
    }

    /**
     * Gets the value of the tt property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTt() {
        return tt;
    }

    /**
     * Sets the value of the tt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTt(String value) {
        this.tt = value;
    }

}
