//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeterAccount complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeterAccount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterIdentifier"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isSmartCard" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeterAccount", propOrder = {
        "accNo",
        "isSmartCard"
})
public class MeterAccount
        extends MeterIdentifier {

    @XmlElement(name = "AccNo")
    protected String accNo;
    protected boolean isSmartCard;

    /**
     * Gets the value of the accNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * Sets the value of the accNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccNo(String value) {
        this.accNo = value;
    }

    /**
     * Gets the value of the isSmartCard property.
     */
    public boolean isIsSmartCard() {
        return isSmartCard;
    }

    /**
     * Sets the value of the isSmartCard property.
     */
    public void setIsSmartCard(boolean value) {
        this.isSmartCard = value;
    }

}
