//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for MeterDetail complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeterDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterConfig"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="meterType" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="unitOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ctRatio" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ptRatio" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ti" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="msno" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sgc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="krn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeterDetail", propOrder = {
        "meterType"
})
@XmlSeeAlso({
        ExtMeterDetail.class
})
public class MeterDetail
        extends MeterConfig {

    protected MeterType meterType;
    @XmlAttribute(name = "unitOfMeasurement")
    protected String unitOfMeasurement;
    @XmlAttribute(name = "ctRatio")
    protected String ctRatio;
    @XmlAttribute(name = "ptRatio")
    protected String ptRatio;
    @XmlAttribute(name = "ti")
    protected String ti;
    @XmlAttribute(name = "msno")
    protected String msno;
    @XmlAttribute(name = "sgc")
    protected String sgc;
    @XmlAttribute(name = "krn")
    protected String krn;

    /**
     * Gets the value of the meterType property.
     *
     * @return possible object is
     * {@link MeterType }
     */
    public MeterType getMeterType() {
        return meterType;
    }

    /**
     * Sets the value of the meterType property.
     *
     * @param value allowed object is
     *              {@link MeterType }
     */
    public void setMeterType(MeterType value) {
        this.meterType = value;
    }

    /**
     * Gets the value of the unitOfMeasurement property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUnitOfMeasurement() {
        return unitOfMeasurement;
    }

    /**
     * Sets the value of the unitOfMeasurement property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnitOfMeasurement(String value) {
        this.unitOfMeasurement = value;
    }

    /**
     * Gets the value of the ctRatio property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCtRatio() {
        return ctRatio;
    }

    /**
     * Sets the value of the ctRatio property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCtRatio(String value) {
        this.ctRatio = value;
    }

    /**
     * Gets the value of the ptRatio property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPtRatio() {
        return ptRatio;
    }

    /**
     * Sets the value of the ptRatio property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPtRatio(String value) {
        this.ptRatio = value;
    }

    /**
     * Gets the value of the ti property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTi() {
        return ti;
    }

    /**
     * Sets the value of the ti property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTi(String value) {
        this.ti = value;
    }

    /**
     * Gets the value of the msno property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMsno() {
        return msno;
    }

    /**
     * Sets the value of the msno property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMsno(String value) {
        this.msno = value;
    }

    /**
     * Gets the value of the sgc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSgc() {
        return sgc;
    }

    /**
     * Sets the value of the sgc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSgc(String value) {
        this.sgc = value;
    }

    /**
     * Gets the value of the krn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKrn() {
        return krn;
    }

    /**
     * Sets the value of the krn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKrn(String value) {
        this.krn = value;
    }

}
