//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;


/**
 * <p>Java class for MsgID complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MsgID"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uniqueNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgID")
public class MsgID {

    @XmlAttribute(name = "dateTime")
    protected String dateTime;
    @XmlAttribute(name = "uniqueNumber")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger uniqueNumber;
    @XmlAttribute(name = "sequenceNumber")
    protected String sequenceNumber;

    /**
     * Gets the value of the dateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the uniqueNumber property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getUniqueNumber() {
        return uniqueNumber;
    }

    /**
     * Sets the value of the uniqueNumber property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setUniqueNumber(BigInteger value) {
        this.uniqueNumber = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

}
