//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayAccTx complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PayAccTx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}Tx"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tariff" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Tariff" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayAccTx", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "accDesc",
        "accNo",
        "tariff"
})
@XmlSeeAlso({
        DebtRecoveryTx.class,
        ServiceChrgTx.class,
        ConnectionTx.class,
        ConversionTx.class,
        TamperTx.class,
        UpgradeTx.class
})
public class PayAccTx
        extends Tx {

    protected String accDesc;
    protected String accNo;
    protected Tariff tariff;

    /**
     * Gets the value of the accDesc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccDesc() {
        return accDesc;
    }

    /**
     * Sets the value of the accDesc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccDesc(String value) {
        this.accDesc = value;
    }

    /**
     * Gets the value of the accNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * Sets the value of the accNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccNo(String value) {
        this.accNo = value;
    }

    /**
     * Gets the value of the tariff property.
     *
     * @return possible object is
     * {@link Tariff }
     */
    public Tariff getTariff() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     *
     * @param value allowed object is
     *              {@link Tariff }
     */
    public void setTariff(Tariff value) {
        this.tariff = value;
    }

}
