//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayAccResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PayAccResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseVendResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="payAccReceipt" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}PayAccReceipt" minOccurs="0"/&gt;
 *         &lt;element name="CisVendingServerDetail" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CisVendingServerDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayAccResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "payAccReceipt",
        "cisVendingServerDetail"
})
public class PayAccResp
        extends BaseVendResp {

    protected PayAccReceipt payAccReceipt;
    @XmlElement(name = "CisVendingServerDetail")
    protected CisVendingServerDetail cisVendingServerDetail;

    /**
     * Gets the value of the payAccReceipt property.
     *
     * @return possible object is
     * {@link PayAccReceipt }
     */
    public PayAccReceipt getPayAccReceipt() {
        return payAccReceipt;
    }

    /**
     * Sets the value of the payAccReceipt property.
     *
     * @param value allowed object is
     *              {@link PayAccReceipt }
     */
    public void setPayAccReceipt(PayAccReceipt value) {
        this.payAccReceipt = value;
    }

    /**
     * Gets the value of the cisVendingServerDetail property.
     *
     * @return possible object is
     * {@link CisVendingServerDetail }
     */
    public CisVendingServerDetail getCisVendingServerDetail() {
        return cisVendingServerDetail;
    }

    /**
     * Sets the value of the cisVendingServerDetail property.
     *
     * @param value allowed object is
     *              {@link CisVendingServerDetail }
     */
    public void setCisVendingServerDetail(CisVendingServerDetail value) {
        this.cisVendingServerDetail = value;
    }

}
