//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PinVoucher complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PinVoucher"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}PayType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="voucherSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="voucherPin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="voucherAmount" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PinVoucher", propOrder = {
        "voucherSerialNumber",
        "voucherPin",
        "voucherAmount"
})
public class PinVoucher
        extends PayType {

    protected String voucherSerialNumber;
    protected String voucherPin;
    protected Currency voucherAmount;

    /**
     * Gets the value of the voucherSerialNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVoucherSerialNumber() {
        return voucherSerialNumber;
    }

    /**
     * Sets the value of the voucherSerialNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVoucherSerialNumber(String value) {
        this.voucherSerialNumber = value;
    }

    /**
     * Gets the value of the voucherPin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVoucherPin() {
        return voucherPin;
    }

    /**
     * Sets the value of the voucherPin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVoucherPin(String value) {
        this.voucherPin = value;
    }

    /**
     * Gets the value of the voucherAmount property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getVoucherAmount() {
        return voucherAmount;
    }

    /**
     * Sets the value of the voucherAmount property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setVoucherAmount(Currency value) {
        this.voucherAmount = value;
    }

}
