//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Receipt complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Receipt"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactions" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}Transactions" minOccurs="0"/&gt;
 *         &lt;element name="MonthlyTotals" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}MonthlyTotals"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="receiptNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Receipt", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "transactions",
        "monthlyTotals"
})
@XmlSeeAlso({
        CreditVendReceipt.class,
        PayAccReceipt.class
})
public abstract class Receipt {

    protected Transactions transactions;
    @XmlElement(name = "MonthlyTotals", required = true, nillable = true)
    protected MonthlyTotals monthlyTotals;
    @XmlAttribute(name = "receiptNo")
    protected String receiptNo;

    /**
     * Gets the value of the transactions property.
     *
     * @return possible object is
     * {@link Transactions }
     */
    public Transactions getTransactions() {
        return transactions;
    }

    /**
     * Sets the value of the transactions property.
     *
     * @param value allowed object is
     *              {@link Transactions }
     */
    public void setTransactions(Transactions value) {
        this.transactions = value;
    }

    /**
     * Gets the value of the monthlyTotals property.
     *
     * @return possible object is
     * {@link MonthlyTotals }
     */
    public MonthlyTotals getMonthlyTotals() {
        return monthlyTotals;
    }

    /**
     * Sets the value of the monthlyTotals property.
     *
     * @param value allowed object is
     *              {@link MonthlyTotals }
     */
    public void setMonthlyTotals(MonthlyTotals value) {
        this.monthlyTotals = value;
    }

    /**
     * Gets the value of the receiptNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiptNo() {
        return receiptNo;
    }

    /**
     * Sets the value of the receiptNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiptNo(String value) {
        this.receiptNo = value;
    }

}
