//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordMissing complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RecordMissing"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.eskom.co.za/xmlvend/meter-ext/2.1/schema}DataFault"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reason" type="{http://www.eskom.co.za/xmlvend/meter-ext/2.1/schema}RecordMissingReason" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordMissing", namespace = "http://www.eskom.co.za/xmlvend/meter-ext/2.1/schema", propOrder = {
        "reason"
})
public class RecordMissing
        extends DataFault {

    protected RecordMissingReason reason;

    /**
     * Gets the value of the reason property.
     *
     * @return possible object is
     * {@link RecordMissingReason }
     */
    public RecordMissingReason getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     *
     * @param value allowed object is
     *              {@link RecordMissingReason }
     */
    public void setReason(RecordMissingReason value) {
        this.reason = value;
    }

}
