//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReverseMerchantDepositReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ReverseMerchantDepositReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DepositReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReverseMerchantDepositReq", propOrder = {
        "depositReferenceNumber"
})
public class ReverseMerchantDepositReq
        extends BaseReq {

    @XmlElement(name = "DepositReferenceNumber")
    protected String depositReferenceNumber;

    /**
     * Gets the value of the depositReferenceNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDepositReferenceNumber() {
        return depositReferenceNumber;
    }

    /**
     * Sets the value of the depositReferenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDepositReferenceNumber(String value) {
        this.depositReferenceNumber = value;
    }

}
