//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SalesBatch complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SalesBatch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}Batch"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firstTxSeqNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastTxSeqNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shiftBatch" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}ShiftBatch" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="seqNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesBatch", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "firstTxSeqNo",
        "lastTxSeqNo",
        "shiftBatch"
})
public class SalesBatch
        extends Batch {

    protected String firstTxSeqNo;
    protected String lastTxSeqNo;
    protected List<ShiftBatch> shiftBatch;
    @XmlAttribute(name = "seqNo")
    protected String seqNo;

    /**
     * Gets the value of the firstTxSeqNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFirstTxSeqNo() {
        return firstTxSeqNo;
    }

    /**
     * Sets the value of the firstTxSeqNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFirstTxSeqNo(String value) {
        this.firstTxSeqNo = value;
    }

    /**
     * Gets the value of the lastTxSeqNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastTxSeqNo() {
        return lastTxSeqNo;
    }

    /**
     * Sets the value of the lastTxSeqNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastTxSeqNo(String value) {
        this.lastTxSeqNo = value;
    }

    /**
     * Gets the value of the shiftBatch property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the shiftBatch property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShiftBatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShiftBatch }
     */
    public List<ShiftBatch> getShiftBatch() {
        if (shiftBatch == null) {
            shiftBatch = new ArrayList<ShiftBatch>();
        }
        return this.shiftBatch;
    }

    /**
     * Gets the value of the seqNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSeqNo(String value) {
        this.seqNo = value;
    }

}
