//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaleCredTokenIssue complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SaleCredTokenIssue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CreditTokenIssue"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ctUnits" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Units" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaleCredTokenIssue", propOrder = {
        "ctUnits"
})
public class SaleCredTokenIssue
        extends CreditTokenIssue {

    protected Units ctUnits;

    /**
     * Gets the value of the ctUnits property.
     *
     * @return possible object is
     * {@link Units }
     */
    public Units getCtUnits() {
        return ctUnits;
    }

    /**
     * Sets the value of the ctUnits property.
     *
     * @param value allowed object is
     *              {@link Units }
     */
    public void setCtUnits(Units value) {
        this.ctUnits = value;
    }

}
