//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StartBatchResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StartBatchResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="startedBatch" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}StartBatch" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartBatchResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "startedBatch"
})
public class StartBatchResp
        extends BaseResp {

    protected StartBatch startedBatch;

    /**
     * Gets the value of the startedBatch property.
     *
     * @return possible object is
     * {@link StartBatch }
     */
    public StartBatch getStartedBatch() {
        return startedBatch;
    }

    /**
     * Sets the value of the startedBatch property.
     *
     * @param value allowed object is
     *              {@link StartBatch }
     */
    public void setStartedBatch(StartBatch value) {
        this.startedBatch = value;
    }

}
