//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StepsUnitsCostItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StepsUnitsCostItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StepRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UnitsValue" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Units" minOccurs="0"/&gt;
 *         &lt;element name="CurrencyValue" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StepsUnitsCostItem", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "stepRate",
        "unitsValue",
        "currencyValue"
})
public class StepsUnitsCostItem {

    @XmlElement(name = "StepRate")
    protected String stepRate;
    @XmlElement(name = "UnitsValue")
    protected Units unitsValue;
    @XmlElement(name = "CurrencyValue")
    protected Currency currencyValue;

    /**
     * Gets the value of the stepRate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStepRate() {
        return stepRate;
    }

    /**
     * Sets the value of the stepRate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStepRate(String value) {
        this.stepRate = value;
    }

    /**
     * Gets the value of the unitsValue property.
     *
     * @return possible object is
     * {@link Units }
     */
    public Units getUnitsValue() {
        return unitsValue;
    }

    /**
     * Sets the value of the unitsValue property.
     *
     * @param value allowed object is
     *              {@link Units }
     */
    public void setUnitsValue(Units value) {
        this.unitsValue = value;
    }

    /**
     * Gets the value of the currencyValue property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getCurrencyValue() {
        return currencyValue;
    }

    /**
     * Sets the value of the currencyValue property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setCurrencyValue(Currency value) {
        this.currencyValue = value;
    }

}
