//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;


/**
 * <p>Java class for STS1TokenInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="STS1TokenInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}TokenInfo"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tokenID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="transferAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tokenClass" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}TokenSubClassType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STS1TokenInfo", propOrder = {
        "tokenID",
        "transferAmt",
        "tokenClass"
})
public class STS1TokenInfo
        extends TokenInfo {

    @XmlElement(required = true)
    protected BigDecimal tokenID;
    @XmlElement(required = true)
    protected BigDecimal transferAmt;
    protected TokenSubClassType tokenClass;

    /**
     * Gets the value of the tokenID property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTokenID() {
        return tokenID;
    }

    /**
     * Sets the value of the tokenID property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setTokenID(BigDecimal value) {
        this.tokenID = value;
    }

    /**
     * Gets the value of the transferAmt property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTransferAmt() {
        return transferAmt;
    }

    /**
     * Sets the value of the transferAmt property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setTransferAmt(BigDecimal value) {
        this.transferAmt = value;
    }

    /**
     * Gets the value of the tokenClass property.
     *
     * @return possible object is
     * {@link TokenSubClassType }
     */
    public TokenSubClassType getTokenClass() {
        return tokenClass;
    }

    /**
     * Sets the value of the tokenClass property.
     *
     * @param value allowed object is
     *              {@link TokenSubClassType }
     */
    public void setTokenClass(TokenSubClassType value) {
        this.tokenClass = value;
    }

}
