//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestBreakerResp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TestBreakerResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}NonMeterSpecificEngResp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="testBreaker" type="{http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema}TestBreakerTokenIssue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestBreakerResp", namespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", propOrder = {
        "testBreaker"
})
public class TestBreakerResp
        extends NonMeterSpecificEngResp {

    protected TestBreakerTokenIssue testBreaker;

    /**
     * Gets the value of the testBreaker property.
     *
     * @return possible object is
     * {@link TestBreakerTokenIssue }
     */
    public TestBreakerTokenIssue getTestBreaker() {
        return testBreaker;
    }

    /**
     * Sets the value of the testBreaker property.
     *
     * @param value allowed object is
     *              {@link TestBreakerTokenIssue }
     */
    public void setTestBreaker(TestBreakerTokenIssue value) {
        this.testBreaker = value;
    }

}
