//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TokenSubClassType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TokenSubClassType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="credit" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}CreditTokenSubClassType"/&gt;
 *           &lt;element name="meterManagement" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterSpecificEng"/&gt;
 *           &lt;element name="nonMeterManagement" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}NonMeterSpecificEng"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TokenSubClassType", propOrder = {
        "credit",
        "meterManagement",
        "nonMeterManagement"
})
public class TokenSubClassType {

    @XmlSchemaType(name = "string")
    protected CreditTokenSubClassType credit;
    @XmlSchemaType(name = "string")
    protected MeterSpecificEng meterManagement;
    @XmlSchemaType(name = "string")
    protected NonMeterSpecificEng nonMeterManagement;

    /**
     * Gets the value of the credit property.
     *
     * @return possible object is
     * {@link CreditTokenSubClassType }
     */
    public CreditTokenSubClassType getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     *
     * @param value allowed object is
     *              {@link CreditTokenSubClassType }
     */
    public void setCredit(CreditTokenSubClassType value) {
        this.credit = value;
    }

    /**
     * Gets the value of the meterManagement property.
     *
     * @return possible object is
     * {@link MeterSpecificEng }
     */
    public MeterSpecificEng getMeterManagement() {
        return meterManagement;
    }

    /**
     * Sets the value of the meterManagement property.
     *
     * @param value allowed object is
     *              {@link MeterSpecificEng }
     */
    public void setMeterManagement(MeterSpecificEng value) {
        this.meterManagement = value;
    }

    /**
     * Gets the value of the nonMeterManagement property.
     *
     * @return possible object is
     * {@link NonMeterSpecificEng }
     */
    public NonMeterSpecificEng getNonMeterManagement() {
        return nonMeterManagement;
    }

    /**
     * Sets the value of the nonMeterManagement property.
     *
     * @param value allowed object is
     *              {@link NonMeterSpecificEng }
     */
    public void setNonMeterManagement(NonMeterSpecificEng value) {
        this.nonMeterManagement = value;
    }

}
