//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TokenTypes.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TokenTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CreditVend"/&gt;
 *     &lt;enumeration value="FreeBasicElectricity"/&gt;
 *     &lt;enumeration value="KeyChange1"/&gt;
 *     &lt;enumeration value="KeyChange2"/&gt;
 *     &lt;enumeration value="Verification"/&gt;
 *     &lt;enumeration value="UnknownNonMeterSpecificEng"/&gt;
 *     &lt;enumeration value="DispenserTest"/&gt;
 *     &lt;enumeration value="DisplayRegisterTotals"/&gt;
 *     &lt;enumeration value="DisplayKeyRevision"/&gt;
 *     &lt;enumeration value="DisplayTariffIndex"/&gt;
 *     &lt;enumeration value="DisplayMaxPowerLimit"/&gt;
 *     &lt;enumeration value="DisplayTamperStatus"/&gt;
 *     &lt;enumeration value="DisplayPowerConsumption"/&gt;
 *     &lt;enumeration value="DisplayMeterVersion"/&gt;
 *     &lt;enumeration value="DisplayPowerUnbalanceLimit"/&gt;
 *     &lt;enumeration value="TestDisplayIndicators"/&gt;
 *     &lt;enumeration value="NonDispenserSpecific11"/&gt;
 *     &lt;enumeration value="TestDisconnectionDevice"/&gt;
 *     &lt;enumeration value="UnknownMeterSpecificEng"/&gt;
 *     &lt;enumeration value="MeterSpecificEngKCTReq"/&gt;
 *     &lt;enumeration value="MeterSpecificEngClearTamper"/&gt;
 *     &lt;enumeration value="MeterSpecificEngClearCredit"/&gt;
 *     &lt;enumeration value="MeterSpecificEngClearAllCredit"/&gt;
 *     &lt;enumeration value="MeterSpecificEngPhUnbal"/&gt;
 *     &lt;enumeration value="MeterSpecificEngPwrLmt"/&gt;
 *     &lt;enumeration value="CmftUnknown"/&gt;
 *     &lt;enumeration value="CmftEnableTamperDetection"/&gt;
 *     &lt;enumeration value="CmftDisableTamperDetection"/&gt;
 *     &lt;enumeration value="CmftPrepaymentToPostPayment"/&gt;
 *     &lt;enumeration value="CmftPostpaymentToPrePayment"/&gt;
 *     &lt;enumeration value="CmftRemoteDisconnect"/&gt;
 *     &lt;enumeration value="CmftRemoteReconnect"/&gt;
 *     &lt;enumeration value="CmftEnableUnderVoltage"/&gt;
 *     &lt;enumeration value="CmftDisableUnderVoltage"/&gt;
 *     &lt;enumeration value="CmftEnableOverVoltage"/&gt;
 *     &lt;enumeration value="CmftDisableOverVoltage"/&gt;
 *     &lt;enumeration value="CmftDecommission"/&gt;
 *     &lt;enumeration value="CmftEnterServiceConfigurationMode"/&gt;
 *     &lt;enumeration value="CmftDisableAdministrationMode"/&gt;
 *     &lt;enumeration value="CmftEnableAdministrationMode"/&gt;
 *     &lt;enumeration value="CmftEnableNegativeCreditDisplay"/&gt;
 *     &lt;enumeration value="CmftDisableNegativeCreditDisplay"/&gt;
 *     &lt;enumeration value="CmftEnableRandomConnection"/&gt;
 *     &lt;enumeration value="CmftDisableRandomConnection"/&gt;
 *     &lt;enumeration value="CmftEnableConsumptionRestriction"/&gt;
 *     &lt;enumeration value="CmftDisableConsumptionRestriction"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "TokenTypes", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema")
@XmlEnum
public enum TokenTypes {

    @XmlEnumValue("CreditVend")
    CREDIT_VEND("CreditVend"),
    @XmlEnumValue("FreeBasicElectricity")
    FREE_BASIC_ELECTRICITY("FreeBasicElectricity"),
    @XmlEnumValue("KeyChange1")
    KEY_CHANGE_1("KeyChange1"),
    @XmlEnumValue("KeyChange2")
    KEY_CHANGE_2("KeyChange2"),
    @XmlEnumValue("Verification")
    VERIFICATION("Verification"),
    @XmlEnumValue("UnknownNonMeterSpecificEng")
    UNKNOWN_NON_METER_SPECIFIC_ENG("UnknownNonMeterSpecificEng"),
    @XmlEnumValue("DispenserTest")
    DISPENSER_TEST("DispenserTest"),
    @XmlEnumValue("DisplayRegisterTotals")
    DISPLAY_REGISTER_TOTALS("DisplayRegisterTotals"),
    @XmlEnumValue("DisplayKeyRevision")
    DISPLAY_KEY_REVISION("DisplayKeyRevision"),
    @XmlEnumValue("DisplayTariffIndex")
    DISPLAY_TARIFF_INDEX("DisplayTariffIndex"),
    @XmlEnumValue("DisplayMaxPowerLimit")
    DISPLAY_MAX_POWER_LIMIT("DisplayMaxPowerLimit"),
    @XmlEnumValue("DisplayTamperStatus")
    DISPLAY_TAMPER_STATUS("DisplayTamperStatus"),
    @XmlEnumValue("DisplayPowerConsumption")
    DISPLAY_POWER_CONSUMPTION("DisplayPowerConsumption"),
    @XmlEnumValue("DisplayMeterVersion")
    DISPLAY_METER_VERSION("DisplayMeterVersion"),
    @XmlEnumValue("DisplayPowerUnbalanceLimit")
    DISPLAY_POWER_UNBALANCE_LIMIT("DisplayPowerUnbalanceLimit"),
    @XmlEnumValue("TestDisplayIndicators")
    TEST_DISPLAY_INDICATORS("TestDisplayIndicators"),
    @XmlEnumValue("NonDispenserSpecific11")
    NON_DISPENSER_SPECIFIC_11("NonDispenserSpecific11"),
    @XmlEnumValue("TestDisconnectionDevice")
    TEST_DISCONNECTION_DEVICE("TestDisconnectionDevice"),
    @XmlEnumValue("UnknownMeterSpecificEng")
    UNKNOWN_METER_SPECIFIC_ENG("UnknownMeterSpecificEng"),
    @XmlEnumValue("MeterSpecificEngKCTReq")
    METER_SPECIFIC_ENG_KCT_REQ("MeterSpecificEngKCTReq"),
    @XmlEnumValue("MeterSpecificEngClearTamper")
    METER_SPECIFIC_ENG_CLEAR_TAMPER("MeterSpecificEngClearTamper"),
    @XmlEnumValue("MeterSpecificEngClearCredit")
    METER_SPECIFIC_ENG_CLEAR_CREDIT("MeterSpecificEngClearCredit"),
    @XmlEnumValue("MeterSpecificEngClearAllCredit")
    METER_SPECIFIC_ENG_CLEAR_ALL_CREDIT("MeterSpecificEngClearAllCredit"),
    @XmlEnumValue("MeterSpecificEngPhUnbal")
    METER_SPECIFIC_ENG_PH_UNBAL("MeterSpecificEngPhUnbal"),
    @XmlEnumValue("MeterSpecificEngPwrLmt")
    METER_SPECIFIC_ENG_PWR_LMT("MeterSpecificEngPwrLmt"),
    @XmlEnumValue("CmftUnknown")
    CMFT_UNKNOWN("CmftUnknown"),
    @XmlEnumValue("CmftEnableTamperDetection")
    CMFT_ENABLE_TAMPER_DETECTION("CmftEnableTamperDetection"),
    @XmlEnumValue("CmftDisableTamperDetection")
    CMFT_DISABLE_TAMPER_DETECTION("CmftDisableTamperDetection"),
    @XmlEnumValue("CmftPrepaymentToPostPayment")
    CMFT_PREPAYMENT_TO_POST_PAYMENT("CmftPrepaymentToPostPayment"),
    @XmlEnumValue("CmftPostpaymentToPrePayment")
    CMFT_POSTPAYMENT_TO_PRE_PAYMENT("CmftPostpaymentToPrePayment"),
    @XmlEnumValue("CmftRemoteDisconnect")
    CMFT_REMOTE_DISCONNECT("CmftRemoteDisconnect"),
    @XmlEnumValue("CmftRemoteReconnect")
    CMFT_REMOTE_RECONNECT("CmftRemoteReconnect"),
    @XmlEnumValue("CmftEnableUnderVoltage")
    CMFT_ENABLE_UNDER_VOLTAGE("CmftEnableUnderVoltage"),
    @XmlEnumValue("CmftDisableUnderVoltage")
    CMFT_DISABLE_UNDER_VOLTAGE("CmftDisableUnderVoltage"),
    @XmlEnumValue("CmftEnableOverVoltage")
    CMFT_ENABLE_OVER_VOLTAGE("CmftEnableOverVoltage"),
    @XmlEnumValue("CmftDisableOverVoltage")
    CMFT_DISABLE_OVER_VOLTAGE("CmftDisableOverVoltage"),
    @XmlEnumValue("CmftDecommission")
    CMFT_DECOMMISSION("CmftDecommission"),
    @XmlEnumValue("CmftEnterServiceConfigurationMode")
    CMFT_ENTER_SERVICE_CONFIGURATION_MODE("CmftEnterServiceConfigurationMode"),
    @XmlEnumValue("CmftDisableAdministrationMode")
    CMFT_DISABLE_ADMINISTRATION_MODE("CmftDisableAdministrationMode"),
    @XmlEnumValue("CmftEnableAdministrationMode")
    CMFT_ENABLE_ADMINISTRATION_MODE("CmftEnableAdministrationMode"),
    @XmlEnumValue("CmftEnableNegativeCreditDisplay")
    CMFT_ENABLE_NEGATIVE_CREDIT_DISPLAY("CmftEnableNegativeCreditDisplay"),
    @XmlEnumValue("CmftDisableNegativeCreditDisplay")
    CMFT_DISABLE_NEGATIVE_CREDIT_DISPLAY("CmftDisableNegativeCreditDisplay"),
    @XmlEnumValue("CmftEnableRandomConnection")
    CMFT_ENABLE_RANDOM_CONNECTION("CmftEnableRandomConnection"),
    @XmlEnumValue("CmftDisableRandomConnection")
    CMFT_DISABLE_RANDOM_CONNECTION("CmftDisableRandomConnection"),
    @XmlEnumValue("CmftEnableConsumptionRestriction")
    CMFT_ENABLE_CONSUMPTION_RESTRICTION("CmftEnableConsumptionRestriction"),
    @XmlEnumValue("CmftDisableConsumptionRestriction")
    CMFT_DISABLE_CONSUMPTION_RESTRICTION("CmftDisableConsumptionRestriction");
    private final String value;

    TokenTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TokenTypes fromValue(String v) {
        for (TokenTypes c : TokenTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
