//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Transactions complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Transactions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tx" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}Tx" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lessRound" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="tenderAmt" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="change" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="units" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transactions", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "tx",
        "lessRound",
        "tenderAmt",
        "change",
        "units"
})
public class Transactions {

    protected List<Tx> tx;
    protected Currency lessRound;
    protected Currency tenderAmt;
    protected Currency change;
    protected Currency units;

    /**
     * Gets the value of the tx property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the tx property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTx().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tx }
     */
    public List<Tx> getTx() {
        if (tx == null) {
            tx = new ArrayList<Tx>();
        }
        return this.tx;
    }

    /**
     * Gets the value of the lessRound property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getLessRound() {
        return lessRound;
    }

    /**
     * Sets the value of the lessRound property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setLessRound(Currency value) {
        this.lessRound = value;
    }

    /**
     * Gets the value of the tenderAmt property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getTenderAmt() {
        return tenderAmt;
    }

    /**
     * Sets the value of the tenderAmt property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setTenderAmt(Currency value) {
        this.tenderAmt = value;
    }

    /**
     * Gets the value of the change property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getChange() {
        return change;
    }

    /**
     * Sets the value of the change property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setChange(Currency value) {
        this.change = value;
    }

    /**
     * Gets the value of the units property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setUnits(Currency value) {
        this.units = value;
    }

}
