//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrialImpulseVendReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TrialImpulseVendReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}CreditVendReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sgc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Krn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TariffIndex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrialImpulseVendReq", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "sgc",
        "krn",
        "tariffIndex"
})
public class TrialImpulseVendReq
        extends CreditVendReq {

    @XmlElement(name = "Sgc")
    protected String sgc;
    @XmlElement(name = "Krn")
    protected String krn;
    @XmlElement(name = "TariffIndex")
    protected String tariffIndex;

    /**
     * Gets the value of the sgc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSgc() {
        return sgc;
    }

    /**
     * Sets the value of the sgc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSgc(String value) {
        this.sgc = value;
    }

    /**
     * Gets the value of the krn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKrn() {
        return krn;
    }

    /**
     * Sets the value of the krn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKrn(String value) {
        this.krn = value;
    }

    /**
     * Gets the value of the tariffIndex property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTariffIndex() {
        return tariffIndex;
    }

    /**
     * Sets the value of the tariffIndex property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTariffIndex(String value) {
        this.tariffIndex = value;
    }

}
