//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for VendorStatement complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VendorStatement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accBal" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="availCredit" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Currency" minOccurs="0"/&gt;
 *         &lt;element name="lineItem" type="{http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema}VendorStatementLineItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendorStatement", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "accNo",
        "accBal",
        "availCredit",
        "lineItem"
})
public class VendorStatement {

    protected String accNo;
    protected Currency accBal;
    protected Currency availCredit;
    protected List<VendorStatementLineItem> lineItem;

    /**
     * Gets the value of the accNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * Sets the value of the accNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccNo(String value) {
        this.accNo = value;
    }

    /**
     * Gets the value of the accBal property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getAccBal() {
        return accBal;
    }

    /**
     * Sets the value of the accBal property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setAccBal(Currency value) {
        this.accBal = value;
    }

    /**
     * Gets the value of the availCredit property.
     *
     * @return possible object is
     * {@link Currency }
     */
    public Currency getAvailCredit() {
        return availCredit;
    }

    /**
     * Sets the value of the availCredit property.
     *
     * @param value allowed object is
     *              {@link Currency }
     */
    public void setAvailCredit(Currency value) {
        this.availCredit = value;
    }

    /**
     * Gets the value of the lineItem property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the lineItem property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VendorStatementLineItem }
     */
    public List<VendorStatementLineItem> getLineItem() {
        if (lineItem == null) {
            lineItem = new ArrayList<VendorStatementLineItem>();
        }
        return this.lineItem;
    }

}
