//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VendIDMethod complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VendIDMethod"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}IDMethod"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="meterIdentifier" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}MeterIdentifier" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendIDMethod", propOrder = {
        "meterIdentifier"
})
public class VendIDMethod
        extends IDMethod {

    protected MeterIdentifier meterIdentifier;

    /**
     * Gets the value of the meterIdentifier property.
     *
     * @return possible object is
     * {@link MeterIdentifier }
     */
    public MeterIdentifier getMeterIdentifier() {
        return meterIdentifier;
    }

    /**
     * Sets the value of the meterIdentifier property.
     *
     * @param value allowed object is
     *              {@link MeterIdentifier }
     */
    public void setMeterIdentifier(MeterIdentifier value) {
        this.meterIdentifier = value;
    }

}
