//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:54:18 AM CAT 
//


package com.jedco.jedcoinspectionspring.conlog;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerifyReq complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VerifyReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}BaseReq"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="token" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}Token" minOccurs="0"/&gt;
 *         &lt;element name="idMethod" type="{http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema}VendIDMethod" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerifyReq", namespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", propOrder = {
        "token",
        "idMethod"
})
public class VerifyReq
        extends BaseReq {

    protected Token token;
    protected VendIDMethod idMethod;

    /**
     * Gets the value of the token property.
     *
     * @return possible object is
     * {@link Token }
     */
    public Token getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     *
     * @param value allowed object is
     *              {@link Token }
     */
    public void setToken(Token value) {
        this.token = value;
    }

    /**
     * Gets the value of the idMethod property.
     *
     * @return possible object is
     * {@link VendIDMethod }
     */
    public VendIDMethod getIdMethod() {
        return idMethod;
    }

    /**
     * Sets the value of the idMethod property.
     *
     * @param value allowed object is
     *              {@link VendIDMethod }
     */
    public void setIdMethod(VendIDMethod value) {
        this.idMethod = value;
    }

}
